### ISSUE TITLE
the sha3-256 result is not same to the libra cli?

### ISSUE THREAD

**Issue by yqsailor** [perfectmak/libra-core#12]
the sha3-256 result is not same to the libra cli, For example, the first account address generated by the same mnemonic word at the libra cli is different from that generated by this program.

**Comment by perfectmak** [comment]
Thank you for reporting this. This issue is already being tracked too.
I believe it is due to some changes in some of the prefixes/salts. It would be fixed to coform the libra cli version.

**Comment by totiz** [comment]
Yeah, I try to figure it out by comparing this project and Libra source code, I think you choose the right prefixes/salts but there're might something different in encode/decode/convert around types. I think we should logs in Libra project and this project to look deeper.

**Comment by wenshenjun** [comment]
https://github.com/perfectmak/libra-core/pull/13
Fixed here.

**Comment by totiz** [comment]
I tested, it works. great!

**Comment by perfectmak** [comment]
Closed via #13
