### ISSUE TITLE
Transfer Failing Because of Breaking changes in proto files

### ISSUE THREAD

**Issue by codemaveric** [perfectmak/libra-core#19]
see

https://community.libra.org/t/testnet-update-scheduled-for-july-10th-with-breaking-changes/1143

Changes to libra proto have broken transfer operations.

**Comment by wenshenjun** [comment]
update here.  https://github.com/perfectmak/libra-core/pull/20

**Comment by perfectmak** [comment]
This fix has been released as version [1.0.4](https://github.com/perfectmak/libra-core/releases/tag/1.0.4)
