### ISSUE TITLE
Setup CI/CD pipeline for library

### ISSUE THREAD

**Issue by perfectmak** [perfectmak/libra-core#2]
## Summary
Setup a continuous integration system to make contributions and commits easier.

I would prefer using travis ci (because why not).

## Definition of done

- [ ] New commits and PR's should trigger a travis ci build
- [ ] Tagged commits to master should trigger an npm publish

**Comment by smiled0g** [comment]
@perfectmak anyone taking this on yet? If no I'd to volunteer.

**Comment by perfectmak** [comment]
@smiled0g No one has taken this yet. Please go for it. Let me know if there is anything I should provide on my end.

**Comment by perfectmak** [comment]
@smiled0g I would like to know if you are still going to work on this.

**Comment by suraneti** [comment]
@perfectmak I can setup travis ci for you, so you have to invite me to be admin of this repo? (read only permission)

**Comment by perfectmak** [comment]
Hi @suraneti thank you. Could you set it up on a fork from your repository and open a PR for it here, I'll enable travis CI on this repository as well.

Then we can sync up from there

**Comment by suraneti** [comment]
@perfectmak I've PR #30. If I had missed some config in a config file you can tell me.
