### ISSUE TITLE
This project was mentioned on CNBC/CSPAN

### ISSUE THREAD

**Issue by icodeforlove** [perfectmak/libra-core#22]
https://www.c-span.org/video/?c4808083/rust-language-chosen&fbclid=IwAR1K74UXQY4hZhvlyxV_LdT4XnePJA-G2PNoKvAxsTx83JPaBqUzGHosN2Y

The congressman mistakenly assumed that this project is the official libra project.

**Comment by perfectmak** [comment]
Yes, I admit the name `libra-core` might be misleading to people who don't use the library. Perhaps I should update the readme and state that it is just a client 🙂and not the official rust codebase.

**Comment by icodeforlove** [comment]
Maybe a little disclaimer could be helpful.

Nevertheless its fun seeing a congressman speak technical.

**Comment by perfectmak** [comment]
Yes, I'll update the readme shortly.

**Comment by georgeokez** [comment]
Really interesting seeing a congressman speak technical jargon...
