### ISSUE TITLE
Storing the account object for later use in transfer coins

### ISSUE THREAD

**Issue by matt454** [perfectmak/libra-core#23]
Hi, 

I'm trying to store the generated account from a wallet for future use in the transfer coins function. I'm not sure how to do this. I can't convert it to JSON or output it to a file without getting [object object]

`const wallet = new LibraWallet();
  const account = wallet.newAccount();

  console.log(account); // How do I store this?`

**Comment by perfectmak** [comment]
I see what you mean, the best way to store an accounts information would be to extracts its private key and store it in an encoded format of your choice. A way I would go about this is to store the private key as hex values and then I can re-create the wallet using the private key. Here is a sample code of how this can be done:

```javascript
const privateKey = account.keypair.getSecretKey();
const privateKeyHex = Buffer.from(privateKey).toString('hex');
// you can persist the privateKeyHex string as you wish
// then later on you can recreate the account object by
const recreatedAccount = Account.fromSecretKey(privateKeyHex);
```

**Comment by matt454** [comment]
Perfect, thanks!

On this line: 

`
account.keyPair.getSecretKey();
`
The key**P**air - p should be uppercase.
