### ISSUE TITLE
Keep getting the same libra hex address when creating an account

### ISSUE THREAD

**Issue by kenken64** [perfectmak/libra-core#25]
{
    "address": "**7315805ae2a470e455bfd5ef3720db0dde16f9688fc25696dc69c8d124b46c1c**",
    "mnemonic": "camera antique meat absent middle blouse hawk figure submit hope thunder rule"
}

{
    "address": "**7315805ae2a470e455bfd5ef3720db0dde16f9688fc25696dc69c8d124b46c1c**",
    "mnemonic": "palm develop normal arrange know joy grocery peasant wish salt stadium fire"
}

{
    "address": "**7315805ae2a470e455bfd5ef3720db0dde16f9688fc25696dc69c8d124b46c1c**",
    "mnemonic": "edit remain buddy shaft help blossom weird will obtain vibrant canvas shadow"
}

**Comment by kenken64** [comment]
app.post(`${API_URL}/account`, (req, res) => {
  const jsonData = req.body;
  console.log(bip39);
  const generatedMnemonic = bip39.generateMnemonic();
  const wallet = new LibraWallet({
    mnemonic: generatedMnemonic
  });
  let account = null;

  if (typeof jsonData.secretkey !== "undefined") {
    console.log(jsonData.secretkey);
    account = LibraAccount.fromSecretKey(jsonData.secretkey);
  } else {
    account = wallet.newAccount();
  }
  let accountCreated = {
    address: account.getAddress().toHex(),
    mnemonic: generatedMnemonic
  };
  res.status(200).json(accountCreated);
});

**Comment by kenken64** [comment]
I know why it keep going to the below codes

account = LibraAccount.fromSecretKey(jsonData.secretkey);

so how can we generate a unique secret key whenever I use the same secret key it generates the same hex address

**Comment by kenken64** [comment]
sorry press the wrong button

**Comment by perfectmak** [comment]
@kenken64 Happy, you fixed your issue.

Yes, I wouldn't advice generating secret keys directly. You can use the wallet with a newly generated mnemonic to create a new account and then extract its secret key.
