### ISSUE TITLE
[BUG] getting unknown error when transferCoins

### ISSUE THREAD

**Issue by mmsqe** [perfectmak/libra-core#26]
Steps to reproduce:

`npm run test`

Current test fails with response as below:
```
acStatus: -1,
mempoolStatus: -1,
vmStatus: LibraVMStatusError {
  errorType: 1,
  validationStatusError: { code: 11, message: 'none' },
  verificationStatusErrors: undefined,
  invariantViolationError: undefined,
  deserializationError: undefined,
  executionError: undefined
}
```

**Comment by perfectmak** [comment]
Thank you for reporting this, I'll look into this as soon as possible.
I believe it might be as a result of this: https://community.libra.org/t/testnet-update-july-24th/1362

**Comment by totiz** [comment]
@perfectmak  Yeah I found it that validationStatusError code 11, which is UnknownScript  that can be transaction script changed or something related.

The script's not in the list below.

https://github.com/libra/libra/blob/327ae96bdcdf748a219201914e0726b3de954192/config/data/configs/node.config.toml
whitelist = [
      "587b2d840dab19bd0f7412e1ca9fc3e50c0d790ca97e8bc5437934faa5c29a94",
      "59c9d8d9e4d2b2eb5b60b2d19cbd33b407c0c2c164091947584ac48687593ecf",
      "25e78410bf55d2f232d321722f1be3e8ba82a1b7198a79bc9c878bc4270773dd",
      "e5cf5c50f35e09564df21d1cdfdf03cb393a837166e1c5237eb2d8b1a884abe2"
  ]

**Comment by perfectmak** [comment]
Yes, I've created a fix for this here: https://github.com/perfectmak/libra-core/pull/27

I'll be making a release soon.

**Comment by perfectmak** [comment]
Released a 1.0.5 version https://github.com/perfectmak/libra-core/releases/tag/1.0.5.

Please test it and let me know if it solves the problem. Then we can close this issue.

**Comment by mmsqe** [comment]
Thanks, transfer works, feel free to close this issue. Just curious how you compile to get `peerToPeerTxn` constant?

**Comment by perfectmak** [comment]
I modified the libra codebase to get the base64 encoded value for peer to peer transactions and that is what I used here.

The ideal solution would be to compile the mvir program and encode it in the library but currently don't have the bandwidth to make that work in nodejs and maintain compatibility.
