### ISSUE TITLE
Transferring between accounts on testnet

### ISSUE THREAD

**Issue by jiaochangyang** [perfectmak/libra-core#34]
Since last Wednesday, there seems to have been a bug where any transaction, either minting or between two accounts, increments sequence_number/send_events_count/receive_events_count increments by 256 per transaction done. Moreover, only one transfer transaction can be sent between two accounts. This does not happen in the official Libra client after updating to latest testnet branch code, but it did happen pre-update.

Thanks!

**Comment by totiz** [comment]
The real problem is not about event count increase from 1 to 256 as the codebase can handle that. But there's a small change to account structure that need to handle new field. I already open this PR https://github.com/perfectmak/libra-core/pull/33 to fix this problem.

**Comment by totiz** [comment]
We can close this issue now, already merged and fixed in release 1.0.6.

**Comment by jiaochangyang** [comment]
Great. Thank you!
